# Site settings
title: DarkCLog
header-img: img/home-bg.jpg
email: hkclex@gmail.com
description: "iOS Developer, Gamer"
baseurl: ""
url: ""
twitter_username:
github_username:  darkcl
facebook_username:

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
